### ISSUE TITLE
Can't install Stitch v0.29.4 on Mac VSCode

### ISSUE THREAD

**Issue by Adrian-Nelson** [bscotch/stitch#106]
I'm using the latest version of VSCode (currently v1.79.2 May 2023) on an Intel based MacBook Pro (running Ventura 13.4.1).

When I click on 'Install' it reports "Can't install release version of 'scotch.bscotch-stitch-vscode' extension because it has no release version" - which is plainly incorrect as the extension is listed as v0.29.4

I've checked that the extensions install ok (I just installed the GitHub CoPilot extension) - and they do - so it's definitely something with the Stitch extension.

Let me know if you need any further info - thanks

**Comment by svioletg** [comment]
Stitch only has pre-release versions available, there should be a "Switch to Pre-release Version" button somewhere, I remember having to set that. If it's not next to the install button already, check if its in the install button's dropdown menu (the arrow attached to it)

**Comment by Adrian-Nelson** [comment]
Ah - that explains it - and yes, switching to pre-release version worked - many thanks
