### ISSUE TITLE
Stitch expects `default` to be the last case despite being valid in GameMaker

### ISSUE THREAD

**Issue by NyakoFox** [bscotch/stitch#110]
![image](https://github.com/bscotch/stitch/assets/87289390/c0dfa576-81e0-463f-acd1-d3aab9ba2d85)

(This is an example, not my actual code lol)

I noticed this when I opened a project in VSCode; my valid GML was throwing syntax errors because of this.

**Comment by adam-coster** [comment]
Huh. I had no idea that was valid syntax. Doesn't it just skip the last case?

**Comment by adam-coster** [comment]
I'm going to close this as a wont-fix since that's a weird control flow pattern that I can't see any reason to make allowances for. If you have a use case you can explain for why being able to do this is useful, please re-open with that info!

**Comment by NyakoFox** [comment]
Whoops, I completely forgot to respond. Here's my use-case:
![image](https://github.com/bscotch/stitch/assets/87289390/bd23b596-3a9e-4187-8f60-6bda8ad28aad)

When the camera mode is undefined, it should default to targeting an object, which passes through to the next type. The `default` is there in case there's a missing or unhandled camera type.
