### ISSUE TITLE
Audio groups aren't recognized, giving an undeclared symbol error

### ISSUE THREAD

**Issue by svioletg** [bscotch/stitch#112]
These audio group names aren't recognized anywhere, it seems they're listed in the project's `.yyp` file under `"AudioGroups"` if that would help point to a solution.

![image](https://github.com/bscotch/stitch/assets/16344364/67fa9555-5975-4164-8ffe-f58286d8e8e9)

**Comment by adam-coster** [comment]
Should be resolved in the latest version (1.8.3)
