### ISSUE TITLE
sprite_get_info() struct contents are unsupported

### ISSUE THREAD

**Issue by BscotchSeth** [bscotch/stitch#113]
https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Asset_Management/Sprites/Sprite_Information/sprite_get_info.htm

The struct returned by sprite_get_info() contains a bunch of known variables, but Stitch doesn't know these. Example:
![image](https://github.com/bscotch/stitch/assets/26627245/02fc83fc-ea63-4146-a969-7622871c2dce)

**Comment by adam-coster** [comment]
Resolved in 1.8.4

This type is not provided in the GameMaker spec, so I had to add it in the code. I converted all of the docs' tables to CSVs and had ChatGPT + Code Interpreter convert them into JavaScript objects to speed that up.
