### ISSUE TITLE
Child structs don't detect parent variables

### ISSUE THREAD

**Issue by NyakoFox** [bscotch/stitch#114]
![image](https://github.com/bscotch/stitch/assets/87289390/1d46018e-7f3d-4520-acec-fb3e73c856d1)

`variable` should be valid in `Child`, but "Undeclared symbol `variable`" appears.

**Comment by adam-coster** [comment]
Yep, this is on the top of my feature list!

**Comment by adam-coster** [comment]
This should be resolved for global constructors in v1.12.0, which will be available soon.
