### ISSUE TITLE
Stitch v1.8.4 cannot open my project

### ISSUE THREAD

**Issue by Adrian-Nelson** [bscotch/stitch#115]
Have opened VSCode at the root of my repo and gone to Stitch and it does not like my project, here is the log:
[Stitch v1.8.4 log.txt](https://github.com/bscotch/stitch/files/12059030/Stitch.v1.8.4.log.txt)

and for good measure here is my project .yyp file:
[Tomb Saver.yyp.txt](https://github.com/bscotch/stitch/files/12059033/Tomb.Saver.yyp.txt)

I hope that helps, let me know if you need any further info.

Many thanks,
Adrian

**Comment by adam-coster** [comment]
The latest version has some additional logging that might help identify the issue. It looks like Stitch is failing to find a `.yy` file for one of the assets in your project, but I can't guess why with the current logs.

**Comment by adam-coster** [comment]
Also, what operating system are you on?

**Comment by adam-coster** [comment]
Closing for now. Re-open if you have any logs or other information to add!

**Comment by Adrian-Nelson** [comment]
I'm on a MacBook Pro running MacOS Ventura 13.4.1 , attached is the latest log from stitch v1.10.3
[stitch-1.10.3-log.txt](https://github.com/bscotch/stitch/files/12102455/stitch-1.10.3-log.txt)

**Comment by adam-coster** [comment]
It looks like this is due to Stitch trying to find a config file for one of your notes. I updated Stitch to just warn when such a file isn't found instead of crashing.

Once v1.11.1 is live that should resolve the issue!

**Comment by Adrian-Nelson** [comment]
Many thanks - the project now loads.
