### ISSUE TITLE
Stitch VSCode shows an error when parsing `if <expr> then`

### ISSUE THREAD

**Issue by stdc105** [bscotch/stitch#116]
The following code snippet is taken from a library ([GMLive](https://yellowafterlife.itch.io/gamemaker-live)) we are using in our project:

```gml
if(live_enabled)then(function(){ // 1
mt_gml_std_Date=new gml_std_haxe_class(-1,"gml_std_Date");
// some more function definition
);
```

Expected: Since GameMaker builds the project just fine... Stitch shouldn't report an error?
Actual: Stitch is reporting two error on comment 1: 
- on keyword `then`: `Expecting: one of these possible Token sequences: 1. [Function] (omit 40 other candidates) but found: 'then'`
- on keyword `function`: `Expecting: one of these possible Token sequences: 1. [BooleanLiteral] (omit 10 other candidates) but found: 'function'`

This is stopping the parser in the beginning of the file (`GMLive.gml`) and causing an important global `live_result` unprocessed, and all the `if (live_enabled) return live_result` in the object events are showing errors because `live_result` isn't defined in Stitch's perspective.

Bug report environment:
Windows 11 Pro 22H2 (22621.1928)
GameMaker BETA IDE v2023.400.0.324 Runtime v2023.400.0.342
VSCode 1.80.1 (user setup)
Stitch VSCode 1.10.1

**Comment by adam-coster** [comment]
I haven't seen `then` as a GML keyword and can't find it in the docs. Does your sample code mean the same thing as:

```js
if(live_enabled){
  (function(){ // 1
    mt_gml_std_Date=new gml_std_haxe_class(-1,"gml_std_Date");
    // some more function definition
  );
}
```
?

In any event, that's a syntax we've never used and the Stitch Parser doesn't support. Do you have any doc references for this `if() then` syntax you're using?

**Comment by stdc105** [comment]
Here's the documentation: [Beta Manual](https://manual.yoyogames.com/index.htm#t=GameMaker_Language%2FGML_Overview%2FLanguage_Features%2FIf_Else_and_Conditional_Operators.htm)

This is not a syntax we are actively using either. The only instance I found a `then` not in the comments or strings is this exact code sample.

About if your code is equivalent to the library code I provide, I think 99% that's the case. I am not entirely sure only because it seems like that function is only defined but not executed, and I have no idea why it would be there in the first place if it does nothing.

**Comment by adam-coster** [comment]
Yeah I was also wondering why it was defined but not executed. I might as well add the `then` as an optional keyword since it's in the spec, but in any case it's probably worth removing or rewriting that specific code sample if that doesn't break anything!

**Comment by stdc105** [comment]
Haha, if that's our project code I'd be more confident to rewrite it, but GMLive builds a whole GML interpreter just to hot reload code, and I don't have the gut to touch it (at least not yet). Thank you for helping!

**Comment by adam-coster** [comment]
Yeah, fair enough! I just pushed out v1.10.2 that includes the `then` keyword, so that should be resolved once it's available in VSCode.

**Comment by stdc105** [comment]
Welp, the `then` error is gone, but the error of a function inside a pair of parentheses is still there...

Also, I misread the library code -- the anonymous function will get executed at the end. There were too many parentheses, sorry about that! This is a new issue, Stitch doesn't understand "self-executing anonymous function" syntax, i.e. `(function() { /* do something */ })()`. It will report 2 errors, first on `function` (same as the second one in the issue, `function` unexpected), and second on the last closing parenthesis (`Redundant input, expecting EOF but found: )`).

**Comment by adam-coster** [comment]
Ah, yeah, that makes more sense. I tried a few experiments to see if I could get IIFE support working, but it would require some changes to the most recursive part of the parser and I couldn't make it work with a cursory try. Or, anyway, I couldn't make it work without causing other problems!

The parser logic is all here if you decide to try to figure it out yourself: https://github.com/bscotch/stitch/blob/develop/packages/parser/src/parser.ts

Definitely include test cases if you do!

**Comment by stdc105** [comment]
Great, can't make any promise if I can make it work but I'll try this weekend!
