### ISSUE TITLE
Use in Linguist?

### ISSUE THREAD

**Issue by TheWitheredStriker** [bscotch/stitch#119]
Hey there! Admittedly, this PR isn't _really_ about the development of the VS Code extension itself, but it's still related to it.

I wanted to ask if, perhaps, you could consider suggesting your extension's GML grammar for use in [Linguist](https://github.com/github-linguist/linguist)? Linguist is essentially the provider of GitHub's syntax highlighting. It currently does not have an actual grammar for GML, so they use a C++ highlighter for GML code instead. As you can likely tell, this is not a great reading experience:
![image](https://github.com/bscotch/stitch/assets/38614982/3f37bf7d-3a80-4f40-9f9b-752aeb1c9656)

I've tested Stitch's grammar in [NovaLightshow](https://novalightshow.netlify.app/) and it works splendidly. It'd be great to have proper syntax highlighting for GML on GitHub, thus why I suggest this.

Hope you're having a great day!

EDIT: [Link](https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md) to the documentation on how to add/replace grammars, if you are interested. [More important info here](https://github.com/github-linguist/linguist/discussions/6019).

**Comment by adam-coster** [comment]
That's a good idea! I'm not sure when I'll find the time to submit it, but if there's anything I can do on this side to make submission easier please let me know. Feel free to submit it yourself -- otherwise whenever I find the time someday I'll do so!

**Comment by TheWitheredStriker** [comment]
Bet! I'll try to submit it myself if I can get WSL to work again (the Linguist scripts do not like Windows xD), but if it doesn't work, I'll put an explanation here of how to do it. In that case, take your time above all!

**Comment by adam-coster** [comment]
Given that GameMaker is moving more stuff towards open source, and that they appear to plan to support TextMate grammars, it would be best if they handled this in a more official capacity. I recommend submitting a ticket directly to them: https://github.com/YoYoGames/GameMaker-Feature-Requests
