### ISSUE TITLE
Checkouts causes Stitch to resave .yyp with lose of some resources

### ISSUE THREAD

**Issue by grif-on** [bscotch/stitch#154]
For some reason the Stitch extension caused some assets entries to be deleted from the .yyp file when making a checkout (switching) of commits in VS Code .
Checkouts work as intended without assets entries lose when Stitch is disabled .

- This happens with commits that are have changes in the .yyp file .
- But commits with changes in .gml works without bug as long as they don't have changes in the .yyp file .

Here is a demonstration video :
https://youtu.be/R1B_NafBqJk

Gamemaker IDE version 2023.6.0.92 (steam latest)
Stitch v1.39.0 (Last updated 2023-9-1, 02:26:30)

**Comment by adam-coster** [comment]
This is probably because Stitch is watching for changes to all project files and trying to keep things in sync, so when you do a checkout Stitch ends up re-saving the yyp file while it's reloading everything. I'll have to do some digging to figure out exactly what the logic problem is.

**Comment by adam-coster** [comment]
@grif-on I believe this is resolved now!
