### ISSUE TITLE
VSCode extenstion stopped loading project since v1.39.0

### ISSUE THREAD

**Issue by Meissnerinc** [bscotch/stitch#158]
Since `v1.39.0` the VSCode extension doesn't load the project via the .yyp file which robs the extension of core functionality like references and so on. Is there a way to force the load? 

(Apologies if this is not the right forum)

**Comment by msvit** [comment]
I can confirm the same issue, I'm on macOS and the activation on any version >= 1.40 fails trying to verify the pixel-checksum.node (not a mach-o file).

(and thanks a LOT for this extension btw)

**Comment by adam-coster** [comment]
@Meissnerinc are you also on Mac?

We're on Windows so I don't test anything on Mac, but it's definitely the case that v1.39.0 added a Windows-specific feature.

I'll see if I can disable that feature on non-Windows platforms to resolve this. Tackling it now!

**Comment by adam-coster** [comment]
v1.48.2 is building now.

It *should* make it so that the Windows-only feature does not get imported on non-Windows platforms, but I don't have a way to test that. Once it's live and you get the chance to try it out, please let me know if the problem is resolved!

**Comment by msvit** [comment]
I can confirm that 1.48.2 update fixed the issue, the extension is now being activated again.

Thanks a lot!

**Comment by Meissnerinc** [comment]
This has been closed already but just want to confirm that I'm also on mac. Thanks for responding so quickly!
