### ISSUE TITLE
Stitch won't open particular project

### ISSUE THREAD

**Issue by nutt-y** [bscotch/stitch#163]
Everytime I try to open my project, I am met with this error:
![image](https://github.com/bscotch/stitch/assets/71405160/5cf4eaec-8ec4-4f8b-b5ea-c13181c7bf06)
D
![image](https://github.com/bscotch/stitch/assets/71405160/90e8f795-2a74-4c26-b93e-9a1c15ca3785)

Is there any debugging that I can do that may be causing this error?

**Comment by adam-coster** [comment]
You can view the extension's logs by opening the Output panel and selecting "Stitch" from the dropdown menu.

**Comment by adam-coster** [comment]
Closing as stale. Feel free to re-open if you have more details to add!
