### ISSUE TITLE
Sprite icon update doesn't occur on import

### ISSUE THREAD

**Issue by sam-coster** [bscotch/stitch#166]
The little sprite icons in both the 'recently imported' list and in the project hierarchy don't update after an import, which then requires manually clicking to spotcheck them and see if the sprite has indeed been properly updated.

**Comment by adam-coster** [comment]
Resolved in v1.54.1, by no longer re-using "Frame IDs" (the random UUIDs generated for each frame), so that VSCode's cache doesn't get in the way.
