### ISSUE TITLE
Need to be able to press F12 on sprites and sounds to view them.

### ISSUE THREAD

**Issue by BscotchSeth** [bscotch/stitch#171]
Currently, pressing F12 to view a sprite or sound will pop up an error saying "No definition found," even when Stitch knows about the asset. Pressing F12 should take me to that asset's viewer, so I can look at the sprite's bounding box (or animations), or so I can listen to the sound in question.

![image](https://github.com/bscotch/stitch/assets/26627245/9bedbc80-6cc1-4bcf-accc-bd146aa5ad5e)

**Comment by adam-coster** [comment]
I think I'm skipping non-code assets since originally Stitch could only meaningfully edit code assets. Since sounds and sprites are now viewable in Stitch this should be straight forward.
