### ISSUE TITLE
Pressing F12 on a built-in function (such as 'array_length') should open the Game Maker Manual page associated with that function.

### ISSUE THREAD

**Issue by BscotchSeth** [bscotch/stitch#172]
Currently, if I want to see documentation for a function, I have to go to Chrome, search for the Game Maker manual, and then type the name of the function in the search box.

In the Game Maker IDE, you can middle-click a built-in function to open the documentation for that function. Stitch should do the same (but with F12)!

Downsides: It's not obvious how they compose their URLs to the function documentation, but... I'M SURE YOU CAN FIGURE IT OUT!

**Comment by adam-coster** [comment]
The URLs can be found in the IDE install directory:

`C:\Program Files\GameMaker\RoboHelp\helpdocs_keywords.json`

The format of this file is:

```ts
type HelpLinks = {[funcName:string]: string};
```

Where the values are the help paths.

To convert these paths into manual links:

```ts
const baseUrl = `https://beta-manual.yoyogames.com/#t=`;
const path = encodeUri(helpLinks[funcName]);
const url = `${baseUrl}${path}.htm` // NOT html!
```

The easy solution is to add a link to the hover-text for built-ins, and this is a good idea *anyway* so I'll definitely do that.

In theory I can trigger any functionality when go-to-definition is used, but that isn't an intended behavior in VSCode so I'm not 100% sure that'll work without jank. We'll give it a shot!
