### ISSUE TITLE
Comment text color incorrect when after macros

### ISSUE THREAD

**Issue by bfrymire** [bscotch/stitch#188]
When putting comments on the same line as macros, the comment text color is incorrect.

![Code_dBuD70SeVE](https://github.com/bscotch/stitch/assets/20096702/599ac35f-3e22-441d-9d44-41c1ff6cadfc)

**Comment by adam-coster** [comment]
Macro lines are tricky to parse since they can sorta contain anything. I'll have to check to see if this is a parsing error or some other problem, but I might not be able to fix it easily.

**Comment by adam-coster** [comment]
Closing for now, since addressing this will require reworking how Macros are handled and that'd be quite the undertaking!
