### ISSUE TITLE
Add naming convention enforcement

### ISSUE THREAD

**Issue by adam-coster** [bscotch/stitch#194]
We ran into an issue with art pipeline configuration where we forgot to add the `"prefix": "sp_"` option, resulting in a bunch of sprites missing that prefix and thus requiring a bunch of manual fixing (since our workflows and tools assume that all sprite names start with `sp_`).

Stitch should allow enforcement of conventions like this at the project level, which it could carry through all Stitch features (including the art pipelines). The stitch config file adjacent to the `yyp` (which currently is just use for texture page assignments) is a natural place to handle this.

Naming conventions could be enforced during asset renaming, asset creation, and in the sprite import pipeline.

Example of what the config options might look like:

```jsonc
{
  // ... other stuff
  "nameConventions": {
    "sprites": {
      "prefix": "sp_", // For simple cases where a pattern isn't needed. Would also work as the "default" if that isn't specified
      "pattern": "^sp_[a-z0-9_]+", // Regex pattern for robust validation of names
      "default": "sp_" // Optional, for placeholders during renaming/asset creation. Falls back to "prefix" when set.
    }
  }
}
```

@BscotchSeth Does this seem like it solves problems usefully? Any related features you could use?

**Comment by BscotchSeth** [comment]
Looks good! This will be super useful.

**Comment by adam-coster** [comment]
Partially implemented. For sprites and audio, adding new resources through Stitch VSCode will enforce rules specified in the `stitch.config.json` file. Will need to also apply to *image pipelines* to finish the task.
