### ISSUE TITLE
Add the ability to manage included files through Stitch.

### ISSUE THREAD

**Issue by BscotchSeth** [bscotch/stitch#197]
Currently, included files are not visible or manageable through Stitch. Some notes about them:

* In general, they are generic files with no opinions about their contents or formatting. They have no associated `.yy` file.
* Included files live in the `datafiles` folder within the project, and they can have sub-folders.
* They must be registered in the `.yyp` project file, or the runner will not export them into its cache, meaning they won't be accessible.

I want to be able to do the following:
* See included files in the Stitch asset tree.
* Add included files via a right-click menu in the Stitch asset tree.
* Move included files in the asset tree via click-dragging.
* Create folders in the Included Files section to keep them organized.
* Delete included files.

Currently, this all has to be done through the Windows Explorer while the Game Maker IDE is running, because it has a file watcher that will update the `.yyp` file when included files change.

Examples of included files in the `.yyp` file:

```
{"resourceType":"GMIncludedFile","resourceVersion":"1.0","name":"english_export.json","CopyToMask":-1,"filePath":"datafiles/GameData",},
{"resourceType":"GMIncludedFile","resourceVersion":"1.0","name":"gamechanger.json","CopyToMask":-1,"filePath":"datafiles/GameData",},
{"resourceType":"GMIncludedFile","resourceVersion":"1.0","name":"metadata.json","CopyToMask":-1,"filePath":"datafiles/GameData",},
{"resourceType":"GMIncludedFile","resourceVersion":"1.0","name":"campaign.cl2","CopyToMask":-1,"filePath":"datafiles/GameData/RC",},
{"resourceType":"GMIncludedFile","resourceVersion":"1.0","name":"english_export.json","CopyToMask":-1,"filePath":"datafiles/GameData/RC",},
{"resourceType":"GMIncludedFile","resourceVersion":"1.0","name":"gamechanger.json","CopyToMask":-1,"filePath":"datafiles/GameData/RC",},
{"resourceType":"GMIncludedFile","resourceVersion":"1.0","name":"metadata.json","CopyToMask":-1,"filePath":"datafiles/GameData/RC",},
```

**Comment by adam-coster** [comment]
Added in v1.60.0!

Since the built-in file Explorer view is fully-featured, that's the best place to manage Included Files (rather than trying to recreate all of that functionality in Stitch). Stitch's feature related to this are to make doing that easier.
