### ISSUE TITLE
Renaming an object doesn't rename it in the rooms that object is placed in.

### ISSUE THREAD

**Issue by BscotchSeth** [bscotch/stitch#235]
Replication:
* Start a new project using Stitch's "New Project function
* Rename the object `o_init` to something else
* Observe that the project no longer compiles, because the room `rm_init` still references an object called `o_init` which doesn't exist

**Comment by adam-coster** [comment]
Yup, that makes sense. The renaming logic only works on filenames and symbols, and doesn't check in room YY files for those object names. Should be an easy fix.
