### ISSUE TITLE
Object events in a single window

### ISSUE THREAD

**Issue by MayitaMayoso** [bscotch/stitch#240]
Not entirely sure if a similar issue has been reported or if this is even an already existing feature that I do not know how to enable. But I think it would be really nice to be able to have all the object events in a single window. Also being able to create new events just with plain text (ex: on gmedit you can #event create in order to specify that the following lines belong to the create event) would be very useful.

**Comment by adam-coster** [comment]
Would definitely be cool, but VSCode is very file-based. It's technically possible using virtual file systems and other tricks, but that gets very complicated very fast. GMEdit has that pattern as part of its core design, but the entire editor is custom so YAL didn't have to fight against an existing platform.

Might be something to experiment with in the future, but definitely out of scope for our current use case!
