### ISSUE TITLE
@type causes undeclared system

### ISSUE THREAD

**Issue by mathew-odwyer** [bscotch/stitch#248]
Take the following scenario:

```gml
/// @instancevar {Real} foo

/// @type {Id.Socket}
/// @description The bar.
bar = undefined;

_func = function()
{
    foo = 0;
}
```

This causes an error that shows:

> Undeclared symbol `foo`

Also in some scenarios it also shows

> Struct literal shorthand requires an existing variable named "foo"

**Comment by adam-coster** [comment]
I can't replicate this. When I paste that sample code into an object I get the expected hovers and no errors. There must be some additional context causing this.

https://github.com/user-attachments/assets/ec7ae6a1-49a9-4cda-b55d-8782a14e6d28

- Is this code in an Object's Create event?
- Do you get the same outcome if you put that same code into a new Object's Create event?
- Are you getting this issue in the Stitch for VSCode extension? If so, are you on the latest version? If you're getting this from running the parser directly, are you on the latest version?
- What version of GameMaker is your project using?
- Does this issue persist when you restart VSCode?

**Comment by adam-coster** [comment]
Closing for now. Please re-open if you have additional context I can use to try to replicate it!
