### ISSUE TITLE
Spine Collision type on sprite causes project to not load

### ISSUE THREAD

**Issue by tredfern** [bscotch/stitch#258]
A collision mask setting in Gamemaker editor for sprites is "Spine Collision" which has the enum value 6. When loading a project that contains that value in Stitch, the project will fail to load with an "Invalid enum value" message. 

I'm not sure if the value has any consequences beyond just accepting the enum value as a valid option.

**Comment by adam-coster** [comment]
Whoops, that one must not be listed for regular sprites. It's now in the latest version, so that loading failure should be resolved!
