### ISSUE TITLE
Deleting a project breaks the UI

### ISSUE THREAD

**Issue by adam-coster** [bscotch/stitch#39]
Removing a project puts the app into a state where it is unable to set any remaining project as the current one.

No errors are shown, and rebooting the app doesn't help.

Temporary workaround:

1. Open Stitch Desktop
2. Go to Settings (bottom left)
3. Click the `configuration file` link at the top
4. Manually edit the JSON file to change the current project from `null` to an existing `id` from one of the projects
5. Restart Stitch Desktop

**Comment by WangleLine** [comment]
This just happened on my end too.

**Comment by adam-coster** [comment]
Closing due to deprecation of Stitch Desktop in favor of [Stitch for VSCode](https://tinybs.co/stitch-vscode).

See #138 for details.
