### ISSUE TITLE
Stitch should skip an invalid spine file with a warning, instead of skipping the whole folder

### ISSUE THREAD

**Issue by patchuby** [bscotch/stitch#51]
It regularly happens that when rigging a new skin, my rigger creates a new temporary skeleton, that's not supposed to be used by the game and so will have no atlases, and be considered an invalid file by stitch. This will cause the whole import batch to fail even though the other spine files are perfectly fine.

For me the expected behaviour would be to have a warning printed, the file skipped and carry on to the next file.

**Comment by adam-coster** [comment]
This is addressed in the new VSCode-based sprite pipeline system, and so Spritely is now deprecated.
