### ISSUE TITLE
Visual Studio Code doesn't open when clicking "Open in VS Code" button

### ISSUE THREAD

**Issue by bfrymire** [bscotch/stitch#67]
**Stitch Desktop:** v0.11.10
**VS Code:** v1.78.0

Nothing happens when clicking on the `Open in VS Code` button. I'm expecting Visual Studio Code to open a new window with the workspace as my project's folder.

**Comment by adam-coster** [comment]
I've heard a handful of similar reports, but cannot replicate the problem on my or any colleague's machines.

I have a suspicion it has something to do with the available terminals on your system. Can you tell me which terminal (if any) you use as your default? For example, do you use Windows Terminal?

**Comment by bfrymire** [comment]
I use either Command Prompt or PowerShell outside of VS Code, and use Git Bash as my default terminal for VS Code.

**Comment by adam-coster** [comment]
Gotcha. I wonder if the current setup only works when you have Windows Terminal, or something. Next time I'm in the code base I'll see if I can add some additional fallbacks.

Note to self for possible fixes:

Stitch Desktop uses `open` from npm, and on my machine I see the command open Windows Terminal before launching VSCode.

Fallbacks I can add include trying to directly launch the VSCode executables:

- `code-insiders.cmd` (should be in path)
- `code.cmd` (should be in path)
- `${process.env.LOCALAPPDATA}/Programs/Microsoft VS Code Insiders/Code - Insiders.exe`
- `${process.env.LOCALAPPDATA}/Programs/Microsoft VS Code/Code.exe`

**Comment by adam-coster** [comment]
Closing due to deprecation of Stitch Desktop in favor of [Stitch for VSCode](https://tinybs.co/stitch-vscode).

See #138 for details.
