### ISSUE TITLE
Save last selection of GameMaker Releases

### ISSUE THREAD

**Issue by bfrymire** [bscotch/stitch#69]
As a developer that's mostly interested in _"stable"_ GameMaker releases during active development, I would like my previous selection of release types to be saved.

When going to the GameMaker Releases page, `lts`, `stable`, and `beta` are all selected every time.

**Comment by adam-coster** [comment]
As someone only interested in beta releases, I totally agree with the idea.

**Comment by adam-coster** [comment]
Closing due to deprecation of Stitch Desktop in favor of [Stitch for VSCode](https://tinybs.co/stitch-vscode).

See #138 for details.

(Also note that this problem is solved in the VSCode extension!)
