### ISSUE TITLE
Show type of gamemaker version (stable, unstable, beta, LTS) next to version text on main page

### ISSUE THREAD

**Issue by WangleLine** [bscotch/stitch#70]
This could be really useful for people like me, who can't remember which exact versions are of which type.

Here's a small mockup of what that could look like:

![original](https://github.com/bscotch/stitch/assets/34343336/447b2f0d-d438-4c86-bb65-ec8049025c50)
![mockup](https://github.com/bscotch/stitch/assets/34343336/864a0739-91dc-44d3-8f5f-860d04dcd4ea)

**Comment by adam-coster** [comment]
Oooh, yeah that's a good idea!

**Comment by adam-coster** [comment]
Closing due to deprecation of Stitch Desktop in favor of [Stitch for VSCode](https://tinybs.co/stitch-vscode).

See #138 for details.
