### ISSUE TITLE
Stitch ENOENT error while adding a project that doesn't have options directory

### ISSUE THREAD

**Issue by bfrymire** [bscotch/stitch#82]
There's some FOSS developers that add `options/` directory in their `.gitignore` to reduce the size of their repo and allow the IDE to recreate the options.

Stitch will display an ENOENT error when adding a project with a missing project directory. GameMaker IDE is usually able to load projects that are missing the options directory.

Here is the repo trying to be added to Stitch:

https://github.com/daikon-games/rt-shell

![Stitch_4zhd59ZwnL](https://github.com/bscotch/stitch/assets/20096702/a814deae-52d3-4470-9669-a6abca6bc30a)

**Comment by adam-coster** [comment]
I believe I've found and addressed the issue. There were two places I could find where Stitch was assuming that folder exists: once when trying to get the display name for a project, and again when trying to find icon images. Those parts of the code no longer assume that the options folder exists.

Updates are auto-released, so the fix should be available soon.

**Comment by bfrymire** [comment]
Looks fixed! Thank you!
